# Generated by Django 4.0 on 2023-02-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0003_alter_contact_date_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='severity',
            field=models.CharField(max_length=20),
        ),
    ]
